version: '3.4'

services:
  fiber1:
    image: fiber1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  db:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password    

volumes:
  dbdata:
